/*
 * Copyright (c) 2012 Citrix Systems, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OxtService.rc
//
#define IDS_SERVICENAME                 100
#define IDR_OXTSERVICE                  101
#define IDR_OXTGUESTSERVICES            102
#define IDS_DISPLAYNAME                 200
#define IDS_SERVICEDESC                 201
#define IDI_ICON1                       201
#define IDS_ATLBASE_NO_HANDLER          401
#define IDS_ATLBASE_SERVICE_STOPPED     402
#define IDS_ATLBASE_SERVICE_STARTED     403
#define IDS_ATLBASE_BAD_SERVICE         404

#define IDS_FAILED_TO_CREATE_OBJECT_LOCK___H_OXTGUESTSERVICES_24         4000
#define IDS_FAILED_TO_OPEN_XENSTORE___HRESUL_OXTGUESTSERVICES_32         4001
#define IDS_FAILED_TO_INITIALIZE_VM_VALUES___OXTGUESTSERVICES_53         4002
#define IDS_MAXIMUM_INSTANCE_COUNT_REACHED___OXTGUESTSERVICES_61         4003
#define IDS_FAILED_TO_CREATE_VMS_EVENT_GUID__OXTGUESTSERVICES_474        4004
#define IDS_FAILED_TO_CREATE_VMS_EVENT___HRE_OXTGUESTSERVICES_492        4005
#define IDS_FAILED_TO_CREATE_ALERTS_EVENT_GU_OXTGUESTSERVICES_532        4006
#define IDS_FAILED_TO_CREATE_ALERTS_EVENT____OXTGUESTSERVICES_550        4007
#define IDS_PRINCIPAL__zS_PERMISSION__zS_OPE_OXTSECURITYHELPER_35        4008
#define IDS_DENY_CHECK_FAILURE___PERMISSION__OXTSECURITYHELPER_1244      4009
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_OXTSECURITYHELPER_1279      4010
#define IDS_ACCESSPERMISSION_OXTSECURITYHELPER_1281                      4011
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_OXTSECURITYHELPER_1301      4012
#define IDS_LAUNCHPERMISSION_LAUNCH_OXTSECURITYHELPER_1303               4013
#define IDS_DENY_REMOTE_CHECK_FOR_zS_DETECTE_OXTSECURITYHELPER_1309      4014
#define IDS_LAUNCHPERMISSION_ACTIVATE_OXTSECURITYHELPER_1311             4015
#define IDS_DENY_CHECK_FOUND_NO_SD_DACL_FOR__OXTSECURITYHELPER_1431      4016
#define IDS_ACCESSPERMISSION_OXTSECURITYHELPER_1433                      4017
#define IDS_DENY_CHECK_FOUND_NO_SD_DACL_FOR__OXTSECURITYHELPER_1476      4018
#define IDS_LAUNCHPERMISSION_OXTSECURITYHELPER_1478                      4019
#define IDS_FAILED_TO_ALLOCATE_SECURITY_ATTR_OXTSECURITYHELPER_1559      4020
#define IDS_FAILED_TO_CREATE_SECURITY_DESCRI_OXTSECURITYHELPER_1569      4021
#define IDS_FAILED_TO_GET_SIZES_FROM_MAKEABS_OXTSECURITYHELPER_1614      4022
#define IDS_FAILED_TO_ALLOCATE_SECURITY_DESC_OXTSECURITYHELPER_1625      4023
#define IDS_FAILED_CREATE_SD_IN_MAKEABSOLUTE_OXTSECURITYHELPER_1644      4024
#define IDS_FAILED_TO_ALLOCATE_XSH_DESCRIPTO_OXTSECURITYHELPER_1689      4025
#define IDS_FAILED_TO_INITIALIZE_COM_SID___E_OXTSECURITYHELPER_1699      4026
#define IDS_FAILED_TO_ALLOCATE_PINTERACTIVSI_OXTSECURITYHELPER_1709      4027
#define IDS_FAILED_TO_ALLOCATE_ADMINS_SID_OXTSECURITYHELPER_1718         4028
#define IDS_FAILED_CREATEWELLKNOWNSID_PINTER_OXTSECURITYHELPER_1727      4029
#define IDS_FAILED_CREATEWELLKNOWNSID_PADMIN_OXTSECURITYHELPER_1736      4030
#define IDS_FAILED_SETENTRIESINACL_PINTERACT_OXTSECURITYHELPER_1755      4031
#define IDS_FAILED_TO_SET_ADMINS_SID_AS_OWNE_OXTSECURITYHELPER_1765      4032
#define IDS_FAILED_TO_SET_ADMINS_SID_AS_GROU_OXTSECURITYHELPER_1773      4033
#define IDS_FAILED_TO_SET_DACL_FOR_SD___ERRO_OXTSECURITYHELPER_1782      4034
#define IDS_SETUPPARAMETERKEY_COULD_NOT_CREA_OXTSERVICE_106           4053
#define IDS_SETUPPARAMETERKEY_COULD_NOT_SET__OXTSERVICE_115           4054
#define IDS_SETUPPARAMETERKEY_COULD_NOT_SET__OXTSERVICE_123           4055
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_OP_OXTSERVICE_145           4056
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_CR_OXTSERVICE_155           4057
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_SE_OXTSERVICE_165           4058
#define IDS_REGISTEREVENTSOURCE_COULD_NOT_SE_OXTSERVICE_176           4059
#define IDS_UNREGISTEREVENTSOURCE_COULD_NOT__OXTSERVICE_193           4060
#define IDS_UPDATESERVICEREGISTRY_COULD_NOT__OXTSERVICE_233           4061
#define IDS_UPDATESERVICEREGISTRY_COULD_NOT__OXTSERVICE_244           4062
#define IDS_UPDATESERVICEREGISTRY_CHANGE_SER_OXTSERVICE_264           4063
#define IDS_UPDATESERVICEREGISTRY_CHANGE_SER_OXTSERVICE_275           4064
#define IDS_FAILED_TO_LOAD_XS2_LIBRARY___ERR_OXTSERVICE_413           4065
#define IDS_FAILED_TO_START__SERVICE_SHOULD__OXTSERVICE_439           4066
#define IDS_FAILED_TO_START_SERVICE_OXTSERVICE_459                    4067
#define IDS_GETVERSIONEX_FAILED_____ERROR__z_OXTSERVICE_537           4068
#define IDS_FAILED_TO_CREATE_SHUTDOWN_EVENT__OXTSERVICE_545           4069
#define IDS_FAILED_TO_CREATE_VMS_EVENT___ERR_OXTSERVICE_553           4070
#define IDS_FAILED_TO_CREATE_VMS_VECTOR_LOCK_OXTSERVICE_561           4071
#define IDS_FAILED_TO_CREATE_ALERTS_VECTOR_L_OXTSERVICE_569           4072
#define IDS_XS2OPEN_FAILED_FOR_START__NOT_RU_OXTSERVICE_689           4073
#define IDS_XS2READ_FAILED_FOR_VM___ERROR__z_OXTSERVICE_697           4074
#define IDS_XS2READ_FAILED_FOR_VM___ERROR__z_OXTSERVICE_720           4075
#define IDS_FAILED_TO_START_TASK_THREAD___ER_OXTSERVICE_730           4076
#define IDS_FAILED_TO_START_VMS_WATCH_THREAD_OXTSERVICE_739           4077
#define IDS_FAILED_TO_START_ALERTS_WATCH_THR_OXTSERVICE_748           4078
#define IDS_XS2OPEN_FAILED_FOR_LOADVMS___ERR_OXTSERVICE_1090          4079
#define IDS_XS2DIRECTORY_NO_VMS_RETURNED____OXTSERVICE_1101           4080
#define IDS_FAILED_TO_RETURN_SYSTEM_DIRECTOR_OXTSERVICE_1248          4081
#define IDS_FAILED_TO_LAUNCH_POWERCFG_TOOL___OXTSERVICE_1261          4082
#define IDS_FAILURE_RETURNED_FROM_POWEROPTS__OXTSERVICE_1282          4083
#define IDS_WLANPROF__WLANAPI_DLL_NOT_FOUND_OXTSERVICE_1302           4084
#define IDS_WLANPROF__ERROR_LOADING_WIFI_API_OXTSERVICE_1306          4085
#define IDS_WLANPROF__ERROR_GETTING_LIST_OF__OXTSERVICE_1310          4086
#define IDS_WLANPROF__ERROR_ADDING_AP__WLAN__OXTSERVICE_1314          4087
#define IDS_WLANPROF__UNKNOWN_FAILURE_ENCOUN_OXTSERVICE_1318          4088
#define IDS_XS2OPEN_FAILED_FOR_WATCHES___ERR_OXTSERVICE_1339          4089
#define IDS_FAILED_TO_OPEN_XENSTORE_VMS_WATC_OXTSERVICE_1349          4090
#define IDS_XS_WATCH_THREAD_SHUTTING_DOWN__OXTSERVICE_1359            4091
#define IDS_WAIT_FAILED_DURING_XS_WATCH_WAIT_OXTSERVICE_1370          4092
#define IDS_UNKNOWN_FAILURE_DURING_XS_WATCH__OXTSERVICE_1378          4093
#define IDS_RECEIVED_XCDIAG_REQUEST_OXTSERVICE_1414                   4094
#define IDS_FAILED_TO_LAUNCH_XCDIAG_TOOL___E_OXTSERVICE_1430          4095
#define IDS_FAILED_TO_OPEN_XCDIAG_OUTPUT_FIL_OXTSERVICE_1465          4096
#define IDS_XCDIAG_OUTPUT_FILE_APPEARS_EMPTY_OXTSERVICE_1476          4097
#define IDS_FAILED_TO_ALLOCATE_MEMORY_FOR_XC_OXTSERVICE_1486          4098
#define IDS_FAILED_TO_ACCESS_XCDIAG_FILE_OXTSERVICE_1502              4099
#define IDS_FAILED_TO_VIEW_XCDIAG_OUTPUT_OXTSERVICE_1520              4100
#define IDS_XCDIAG_ZIP_FILE_SENT__OXTSERVICE_1591                     4101
#define IDS_DOPOST___OPERATION_FAILED___ERRO_OXTSERVICE_1596          4102
#define IDS_DOGET___FAILED_TO_REGISTER_FOR_A_OXTSERVICE_1652          4103
#define IDS_FAILED_TO_OPEN_V4V_CHANNEL_ON_FI_OXTSERVICE_1721          4104
#define IDS_FAILED_TO_PARSE_JSON_SIGNAL___ER_OXTSERVICE_1759          4105
#define IDS_SAFEARRAYACCESSDATA___FAILED___H_OXTSERVICE_1800          4106
#define IDS_ALERTS_THREAD_SHUTTING_DOWN__OXTSERVICE_1825              4107
#define IDS_DOGET___FAILED_TO_RECEIVE_SIGNAL_OXTSERVICE_1831          4108
#define IDS_FAILED_TO_RESET_SIGNAL_REGISTRAT_OXTSERVICE_1838          4109
#define IDS_SAFEARRAYCOPY___FAILED___HRESULT_OXTSERVICE_1875          4110
#define IDS_E_OUTOFMEMORY___HRESULT__0XzX_OXTSERVICE_1881             4111
#define IDS_SAFEARRAYACCESSDATA___FAILED___H_OXTGUESTSERVICES_230        4112
#define IDS_SAFEARRAYACCESSDATA___RETRIEVED__OXTGUESTSERVICES_237        4113
#define IDS_XS_WATCH_THREAD_SHUTTING_DOWN__OXTGUESTSERVICES_301          4114
#define IDS_DOGET___FAILED___ERROR__zD_HTTP__OXTGUESTSERVICES_308        4115
#define IDS_COCREATEINSTANCE_CLSID_XENVMINFO_OXTGUESTSERVICES_378        4116
#define IDS_QUERYINTERFACE_IXENVMINITIALIZE__OXTGUESTSERVICES_385        4117
#define IDS_QUERYINTERFACE_IXENVMINITIALIZE__OXTGUESTSERVICES_391        4118
#define IDS_LOADIMAGEUID_FAILED__IMAGE__zS___OXTGUESTSERVICES_406        4119
#define IDS_DELETING_XCIPLUGIN_RUN_VALUE_FAI_OXTGUESTSERVICES_640        4120
#define IDS_CREATING_XCIPLUGIN_RUN_VALUE_FAI_OXTGUESTSERVICES_652        4121
#define IDS_FAILED_TO_OPEN_XENINP_FILE_HANDL_OXTGUESTSERVICES_674        4122
#define IDS_FAILED_TO_SEND_XENINP_IOCTL_ACCE_OXTGUESTSERVICES_683        4123
#define IDS_FAILED_TO_PARSE_JSON_PROPERTY__ER_OXTSERVICE                 4124
#define IDS_UNEXPECTED_JSON_VALUE__ER_OXTSERVICE                         4125
#define IDS_ARRAY                                                        4126
#define IDS_BOOL                                                         4127
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif

#define ctxLS
